name: Branch Deleted

on:
  delete:

permissions:
  contents: read
  id-token: write

jobs:
  branch-deleted:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Set Environment Variables
        env:
          GITHUB_REF_NAME: ${{ github.ref_name }}
        run: echo "STAGE_NAME=$(echo \"$GITHUB_REF_NAME\" | sed 's/[\/]/-/g' | tr -cd '[:alnum:]-')" >> $GITHUB_ENV

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/advance-appily-com-dev-github
          aws-region: us-east-1

      - name: Setup Node 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Remove SST Stage
        run: |
          echo "Removing stage: $STAGE_NAME"
          npx sst remove --stage=$STAGE_NAME
