name: Destroy Preview Environment

on:
  pull_request:
    types: [closed]

permissions:
  contents: write
  pull-requests: write
  id-token: write
  deployments: write

jobs:
  remove:
    runs-on: ubuntu-latest
    environment: Staging

    # Updated condition to include merges to qa or main
    if: |
      github.event.pull_request.merged == true &&
      (
        (github.event.pull_request.base.ref == 'qa' || github.event.pull_request.base.ref == 'main') &&
        (startsWith(github.event.pull_request.head.ref, 'bugfix-') ||
         startsWith(github.event.pull_request.head.ref, 'bugfix/') ||
         startsWith(github.event.pull_request.head.ref, 'feature-') ||
         startsWith(github.event.pull_request.head.ref, 'feature/'))
      )

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Get merged branch name
        id: get_merged_branch
        run: echo "MERGED_BRANCH=$(echo ${{ github.event.pull_request.head.ref }} | sed 's/[\/]/-/g' | tr -cd '[:alnum:]-')" >> $GITHUB_ENV

      - name: Configure Dev AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID}}:role/advance-appily-com-dev-github
          aws-region: us-east-1

      - name: Setup Node 20
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Cache Next.js Build
        uses: actions/cache@v4
        with:
          path: |
            .next/cache/
            .open-next/
            .sst/
          key: cache-${{ hashFiles('**/pnpm-lock.yaml') }}-${{ hashFiles('**.[jt]s', '**.[jt]xs') }}
          restore-keys: |
            cache-${{ hashFiles('**/pnpm-lock.yaml') }}-

      - name: Install Pnpm
        run: npm install -g pnpm@9.15.2

      - name: Install deps (with cache)
        run: pnpm install

      - name: Remove SST Environment
        run: npx sst remove --stage $MERGED_BRANCH
