name: Build Preview on Push to Feature Branch

on:
  workflow_dispatch:
  push:
    branches:
      - "feature/*"
      - "feature-*"

permissions:
  contents: write
  pull-requests: write
  id-token: write
  deployments: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: Staging
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2

      # - uses: actions/setup-node@v4
      #   with:
      #     node-version: 20

      - name: Configure Dev AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID}}:role/advance-appily-com-dev-github
          aws-region: us-east-1

      # - name: Cache Next.js Build
      #   uses: actions/cache@v4
      #   with:
      #     path: |
      #       .next/cache/
      #       .open-next/
      #       .sst/
      #     key: cache-${{ hashFiles('**/pnpm-lock.yaml') }}-${{ hashFiles('**.[jt]s', '**.[jt]xs') }}
      #     restore-keys: |
      #       cache-${{ hashFiles('**/pnpm-lock.yaml') }}-

      - name: Cache Next.js Build with Bun
        uses: actions/cache@v4
        with:
          path: |
            ~/.sst/
            ~/.bun/install/cache
            ${{ github.workspace }}/.next/cache
          key: ${{ runner.os }}-bun-${{ hashFiles('**/bun.lockb') }}
          restore-keys: |
            ${{ runner.os }}-bun-${{ hashFiles('**/bun.lockb') }}-

      - name: Install projects deps with Bun
        run: bun install

      - name: typecheck
        run: bun typecheck

      - name: Deploy to AWS with SST
        env:
          NEXT_PUBLIC_APP_URL: ${{ vars.NEXT_PUBLIC_APP_URL}}
          NEXT_PUBLIC_CMS_URL: ${{ vars.NEXT_PUBLIC_CMS_URL}}
          NEXT_PUBLIC_GOOGLE_TAG_MANAGER_ID: ${{ vars.NEXT_PUBLIC_GTAG_ID}}
          NEXT_PUBLIC_GTAG_ID: ${{ vars.NEXT_PUBLIC_GTAG_ID}}

        run: sst deploy --stage=${GITHUB_REF_NAME}
