name: 👾 Build Preview on Push to Feature or Dev Branch

on:
  workflow_dispatch:
  push:
    branches:
      - "feature/*"
      - "feature-*"
      - "bugfix/*"
      - "bugfix-*"
      - "dev"
    paths:
      - "src/**"
      - "*.json"

permissions:
  contents: write
  pull-requests: write
  id-token: write
  deployments: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: Staging
    steps:
      - uses: actions/checkout@v4
      # Define an environment variable for the sanitized stage name
      - name: Set Environment Variables
        env:
          GITHUB_REF_NAME: ${{ github.ref_name }}
        run: echo "STAGE_NAME=$(echo \"$GITHUB_REF_NAME\" | sed 's/[\/]/-/g' | tr -cd '[:alnum:]-')" >> $GITHUB_ENV

      - run: "curl -fsSL https://sst.dev/install | bash"

      # - uses: actions/setup-node@v4
      #   with:
      #     node-version: 20

      - name: Configure Dev AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID}}:role/advance-appily-com-dev-github
          aws-region: us-east-1

      - name: Cache Next.js Build
        uses: actions/cache@v4
        with:
          path: |
            .next/cache/
            .open-next/
            .sst/
          key: cache-${{ hashFiles('**/pnpm-lock.yaml') }}-${{ hashFiles('**.[jt]s', '**.[jt]xs') }}
          restore-keys: |
            cache-${{ hashFiles('**/pnpm-lock.yaml') }}-

      - name: Install Pnpm
        run: npm install -g pnpm

      - name: Install projects deps
        run: pnpm install

      - name: Deploy to AWS with SST
        env:
          NEXT_PUBLIC_APP_URL: ${{ vars.NEXT_PUBLIC_APP_URL}}
          NEXT_PUBLIC_CMS_URL: ${{ vars.NEXT_PUBLIC_CMS_URL}}
          NEXT_PUBLIC_GOOGLE_TAG_MANAGER_ID: ${{ vars.NEXT_PUBLIC_GOOGLE_TAG_MANAGER_ID}}
          NEXT_PUBLIC_GTAG_ID: ${{ vars.NEXT_PUBLIC_GTAG_ID}}
          NEXT_PUBLIC_AWS_IDENTITY_POOL_ID: ${{ vars.NEXT_PUBLIC_AWS_IDENTITY_POOL_ID}}
          NEXT_PUBLIC_AWS_APPLICATION_ID: ${{ vars.NEXT_PUBLIC_AWS_APPLICATION_ID}}
          NEXT_PUBLIC_AWS_CLOUDWATCH_RUM_ENDPOINT: ${{ vars.NEXT_PUBLIC_AWS_CLOUDWATCH_RUM_ENDPOINT}}

        run: |
          echo "Deploying to stage: $STAGE_NAME"
          sst deploy --stage=$STAGE_NAME
