name: 🎣 Create Pull Request to Production on Merge to Main

on:
  workflow_dispatch:
  push:
    branches:
      - "main"
    paths:
      - "src/**"
      - "*.json"
      - "*.yaml"
      - "*.json"
      - "*.config.js"
      - "*.config.ts"

permissions:
  id-token: write
  contents: write # Required for pull request operations

jobs:
  create-pull-request-to-production:
    runs-on: ubuntu-latest
    environment: Staging
    steps:
      - uses: actions/checkout@v4

      - name: Create Pull Request to Production
        if: success()
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ACTOR="${{ github.actor }}"
          DATE=$(date)

          gh pr create \
            --base production \
            --head main \
            --title "Auto-Deploy by $ACTOR on $DATE" \
            --body "This pull request was automatically created by GitHub Actions to deploy the latest changes to production."
