name: 🎣 Create Pull Request to Production on Merge to Main

on:
  workflow_dispatch:
    inputs:
      reason:
        description: "Reason for deployment"
        required: false
        default: "No reason provided"
  push:
    branches:
      - "main"
    paths:
      - "src/**"
      - "*.json"
      - "*.yaml"
      - "*.json"
      - "*.config.js"
      - "*.config.ts"

permissions:
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: Staging
    steps:
      - uses: actions/checkout@v4
      - name: Create Pull Request to Production
        if: success()
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          REASON="${{ github.event.inputs.reason || 'No reason provided' }}"
          ACTOR="${{ github.actor }}"
          DATE=$(date)
          gh pr create --base production --head main --title "Auto- Deploy by $ACTOR on $DATE" --body "Reason: $REASON"
